/**
 * The little words that are not part of a name.
 *
 * "Mujhe Karama jaana hai" holds one destination and four words of glue, and telling them apart
 * is what lets a place be recognised in a sentence rather than only on its own.
 *
 * This file used to build a vocabulary for a grammar-biased Vosk decoder as well (decision 013).
 * Vosk is gone — the owner's decision, after it returned "माला एमरेट्स" for Mall of the Emirates
 * once too often — and a grammar is a Kaldi idea that Whisper has no use for: it hears the whole
 * language or it does not, and constraining it is not a thing that can be done. So the grammar
 * builder went with the engine, and what is left is the word list that was always about the
 * sentence rather than about the recogniser.
 */

export const GLUE: readonly string[] = [
  'मुझे',
  'मैं',
  'मै',
  'हम',
  'हमें',
  'आप',
  'मेरा',
  'मेरी',
  'मेरे',
  'यहाँ',
  'वहाँ',
  'इस',
  'उस',
  'यह',
  'वह',
  'को',
  'का',
  'की',
  'के',
  'में',
  'से',
  'तक',
  'पर',
  'और',
  'या',
  'भी',
  'ही',
  'नहीं',
  'हाँ',
  'क्या',
  'कहाँ',
  'कैसे',
  'कितना',
  'कितनी',
  'कौन',
  'कब',
  'क्यों',
  'है',
  'हैं',
  'हूँ',
  'हो',
  'था',
  'थी',
  'चाहिए',
  'सकता',
  'सकती',
  'सकते',
  'करना',
  'बताओ',
  'बताइए',
  'मिलेगा',
  'मिलेगी',
  'मिलता',
  'मिलती',
  'करे',
  'करो',
  'बनाने',
  'आज',
  'कल',
  'दो',
  'देना',
  'भाई',
  'जी',
  'अच्छा',
  'ठीक',
  'थोड़ा',
  'ज़्यादा',
  'पास',
  'दूर',
  'जल्दी',
  'अभी',
  'एक',
  'तीन',
];

/**
 * The same glue as typed rather than spoken. Folding unifies most pairs — "मुझे" and "mujhe"
 * both become `muje` — but not all of them, and typing is the front door now (decision 014).
 * Only the Devanagari list above goes into the recogniser's grammar; this one exists for
 * reading what someone wrote.
 */
export const ROMAN_GLUE: readonly string[] = [
  'mujhe',
  'main',
  'mai',
  'hum',
  'humein',
  'aap',
  'mera',
  'meri',
  'mere',
  'yahan',
  'wahan',
  'is',
  'us',
  'yeh',
  'woh',
  'ko',
  'ka',
  'ki',
  'ke',
  'mein',
  'me',
  'se',
  'tak',
  'par',
  'aur',
  'ya',
  'bhi',
  'hi',
  'nahi',
  'haan',
  'kya',
  'kahan',
  'kaise',
  'kitna',
  'chalo',
  'jaana',
  'jana',
  'hai',
  'hain',
  'wala',
  'wali',
  'paas',
  'pass',
  'near',
  'the',
  'a',
  'to',
  'at',
  'in',
  'on',
  'of',
];
