-- Entitlement. The whole server side of "who has a valid pass", and nothing else.
--
-- There are no accounts (decision 001): no users table, no emails, no phone numbers. The device
-- is the identity. There is also NO IP ADDRESS COLUMN anywhere in this schema, deliberately —
-- see the note at the foot of this file.
--
-- Validity is never asked of this database. The app verifies a signed pass offline with the
-- public key shipped in the bundle (decision 005); these tables exist to issue those signatures,
-- to stop one paid slot being installed on five phones, and to receive what the mic could not
-- understand. If this database is down, every traveller with a pass is unaffected.

create extension if not exists "pgcrypto";

-- --------------------------------------------------------------------------------------------
-- devices — the identity, and the only one
-- --------------------------------------------------------------------------------------------

create table devices (
  -- Generated by the phone (crypto.randomUUID in localStorage) and reported on first contact.
  id uuid primary key,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  -- Coarse and self-reported, for reading the VoiceEvent data by platform. Never a fingerprint:
  -- no user agent string, no screen size, no font list.
  platform text check (platform in ('android', 'ios', 'other')),
  app_version text,
  -- When the phone decided it had arrived in Dubai — the geofence, or the clock moving to Gulf
  -- time. This is the single number entitlement runs on (the Counter Off Time). Null until then,
  -- which is the normal state for a traveller still in India on the free year.
  landed_at timestamptz
);

comment on table devices is
  'One row per install. No account, no contact details, no IP. The device id is the identity.';

-- --------------------------------------------------------------------------------------------
-- families — one purchase covering one to four named devices
-- --------------------------------------------------------------------------------------------

create table families (
  id uuid primary key default gen_random_uuid(),
  -- 1 to 4. Above four is a WhatsApp conversation, not a row here (decision 006).
  slots smallint not null check (slots between 1 and 4),
  created_at timestamptz not null default now(),
  -- Copied onto every pass in the family so all four phones share one end date, and set only
  -- when the buyer's phone reports landing. A pass bought in India waits for the plane.
  counter_off_at timestamptz
);

-- --------------------------------------------------------------------------------------------
-- passes — a signed token per slot. The signature is the product.
-- --------------------------------------------------------------------------------------------

create type pass_kind as enum ('trial-india', 'trial-dubai', 'paid');
create type pass_status as enum ('issued', 'bound', 'revoked');

create table passes (
  id uuid primary key default gen_random_uuid(),
  family_id uuid not null references families (id) on delete cascade,
  -- 1 is the buyer's own phone; 2, 3 and 4 are the QR codes on घर.2.
  slot smallint not null check (slot between 1 and 4),
  kind pass_kind not null,
  status pass_status not null default 'issued',
  counter_off_at timestamptz,
  expires_at timestamptz,
  -- Signed over {id, kind, slot, counter_off_at, expires_at} by a key that exists only as an
  -- edge function secret. It is NEVER in the client bundle, this schema, or a migration.
  signature text not null,
  -- Set when a phone scans the QR and reports the slot. A second phone reporting a slot that is
  -- already bound is rejected at its next sync — which is the whole anti-sharing mechanism.
  device_id uuid references devices (id) on delete set null,
  bound_at timestamptz,
  -- हटाएँ on घर.2: the binding is dropped here and that phone's pass dies at its next sync.
  revoked_at timestamptz,
  constraint one_pass_per_slot unique (family_id, slot),
  constraint bound_passes_have_a_device check (
    (status = 'bound') = (device_id is not null and bound_at is not null)
  )
);

-- The query that runs on every sync: is this phone's slot still its own?
create unique index passes_one_slot_per_device
  on passes (device_id)
  where device_id is not null and status = 'bound';

-- --------------------------------------------------------------------------------------------
-- orders — UPI, by order, never by VPA
-- --------------------------------------------------------------------------------------------

create type order_status as enum ('created', 'paid', 'failed', 'expired');

create table orders (
  id uuid primary key default gen_random_uuid(),
  -- The device that asked for the order. This is how a payment is tied to a phone at all — a raw
  -- VPA QR cannot be, which is why the product does not use one.
  device_id uuid not null references devices (id) on delete restrict,
  family_id uuid references families (id) on delete set null,
  aggregator text not null,
  aggregator_order_id text not null,
  amount_inr integer not null check (amount_inr > 0),
  slots smallint not null check (slots between 1 and 4),
  status order_status not null default 'created',
  created_at timestamptz not null default now(),
  paid_at timestamptz,
  -- The aggregator's webhook body, verbatim, for reconciling a disputed payment. It may contain
  -- a payer VPA or masked card digits: the aggregator's record of who paid, which can be the son
  -- in Pune rather than the traveller. Never read by the app, never sent to a device.
  webhook_payload jsonb,
  constraint one_order_per_aggregator_id unique (aggregator, aggregator_order_id)
);

create index orders_device on orders (device_id, created_at desc);

-- --------------------------------------------------------------------------------------------
-- No access to anyone, by default
-- --------------------------------------------------------------------------------------------
-- RLS on with NO policies means the anon and authenticated keys can read and write nothing. That
-- is intended and is not an oversight: the app has no login, so there is no such thing as "this
-- traveller's own row" for a policy to describe. Every one of these tables is reached only by an
-- edge function using the service role, which checks the device id itself.

alter table devices enable row level security;
alter table families enable row level security;
alter table passes enable row level security;
alter table orders enable row level security;

-- --------------------------------------------------------------------------------------------
-- On the IP address
-- --------------------------------------------------------------------------------------------
-- There is no ip column, and this is a decision, not an omission (docs/decisions/011).
--
-- The product promises a traveller no account and nothing about them collected. An IP address is
-- personal data under the DPDP Act: storing it obliges us to a purpose, a retention period and a
-- deletion path for a person we cannot identify or contact, because we deliberately hold no way
-- to reach them. It buys us nothing the device id does not already give: entitlement is keyed to
-- the device, sharing is caught by the slot uniqueness above, and fraud is the aggregator's job
-- and its data.
--
-- Supabase's own request logs hold IPs for their retention window regardless. That is a platform
-- log, not our record, and it is not joined to anything here.
--
-- If this is overruled, it is one migration: add `last_ip inet` to devices and a retention job.
-- Overruling it should be written down here with the reason.
